name = "EntropicLearning"
uuid = "857d3a31-ba67-457f-9b14-0a8f313fa218"
authors = ["Michael <michael.groom@sydney.edu.au>"]
version = "0.1.0"

[deps]
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
MLJ = "add582a8-e3ab-11e8-2d5e-e98b27df1bc7"
Random = "9a3f8284-a2c9-5f02-9a11-845980a1fd5c"

[compat]
LinearAlgebra = "1.11.0"
MLJ = "0.20.7"
Random = "1.11.0"
