name: Auto-fix Format

on:
  push:
    branches: [ main, dev ]
    paths:
    - '**.jl'
    - '.JuliaFormatter.toml'
  pull_request:
    branches: [ main, dev ]
    paths:
    - '**.jl'
    - '.JuliaFormatter.toml'

# Add permissions for the workflow
permissions:
  contents: write

jobs:
  format:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        # Fetch full history for better git operations
        fetch-depth: 0
        
    - name: Setup Julia
      uses: julia-actions/setup-julia@v1
      with:
        version: '1.9'
        
    - name: Install JuliaFormatter
      run: julia -e 'using Pkg; Pkg.add("JuliaFormatter")'
      
    - name: Format code
      run: julia -e 'using JuliaFormatter; format(".", verbose=true)'
      
    - name: Check for changes
      id: verify-changed-files
      run: |
        if [ -n "$(git status --porcelain)" ]; then
          echo "changed=true" >> $GITHUB_OUTPUT
          echo "Files that would be changed:"
          git status --porcelain
        else
          echo "changed=false" >> $GITHUB_OUTPUT
          echo "No formatting changes needed"
        fi
        
    - name: Commit formatted files
      if: steps.verify-changed-files.outputs.changed == 'true' && github.event_name == 'push'
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add -A
        git commit -m "Auto-format Julia code with JuliaFormatter [skip ci]"
        git push
        
    - name: Comment on PR (if formatting needed)
      if: steps.verify-changed-files.outputs.changed == 'true' && github.event_name == 'pull_request'
      uses: actions/github-script@v7
      with:
        script: |
          github.rest.issues.createComment({
            issue_number: context.issue.number,
            owner: context.repo.owner,
            repo: context.repo.repo,
            body: '**Formatting Issues Found**\n\nThis PR has Julia code formatting issues. Please run the following command locally and push the changes:\n\n```bash\njulia -e "using JuliaFormatter; format(\\".\\")"```'
          })
          
    - name: Fail on formatting issues for PRs
      if: steps.verify-changed-files.outputs.changed == 'true' && github.event_name == 'pull_request'
      run: |
        echo "Code formatting issues found in PR!"
        echo "Please run 'julia -e \"using JuliaFormatter; format(\\\".\\\")\")' locally and push the changes."
        exit 1
